apiVersion: apps/v1
kind: Deployment
metadata:
  name: helper-backend-deployment
spec:
  selector:
    matchLabels:
      app: helper-backend
  replicas: 2 
  template:
    metadata:
      labels:
        app: helper-backend
    spec:
      containers:
      - name: helper-backend
        image: alexbaily/kitchenhelper-backend:latest
        ports:
        - containerPort: 8080
