apiVersion: batch/v1
kind: Job
metadata:
  name: helper-backend
spec:
  template:
    spec:
      containers:
      - name: helper-backend
        image: kitchenhelper-backend
        command: ['app']
        envFrom:
          - configMapRef:
              name: helper-backend-config
      restartPolicy: OnFailure
